In [24]:
import pandas as pd
import requests
import numpy as np

In [25]:
rs=requests.get('https://api.themoviedb.org/3/movie/popular?api_key=703f0b4742b9931be466f7027ee52797').json()
rs

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/3F2EXWF1thX0BdrVaKvnm6mAhqh.jpg',
   'genre_ids': [28, 53, 80, 18, 9648],
   'id': 1306368,
   'original_language': 'en',
   'original_title': 'The Rip',
   'overview': 'Trust frays when a team of Miami cops discovers millions in cash inside a run-down stash house, calling everyone — and everything — into question.',
   'popularity': 577.3256,
   'poster_path': '/p4bW2sJKAwcHuLpfoZK7Zo63osA.jpg',
   'release_date': '2026-01-13',
   'title': 'The Rip',
   'video': False,
   'vote_average': 7.2,
   'vote_count': 376},
  {'adult': False,
   'backdrop_path': '/ebyxeBh56QNXxSJgTnmz7fXAlwk.jpg',
   'genre_ids': [28, 878, 12],
   'id': 1242898,
   'original_language': 'en',
   'original_title': 'Predator: Badlands',
   'overview': 'Cast out from his clan, a young Predator finds an unlikely ally in a damaged android and embarks on a treacherous journey in search of the ultimate adversary.',
   'popularity': 405.5067,
   'poster_path': '/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg',
   'release_date': '2025-11-05',
   'title': 'Predator: Badlands',
   'video': False,
   'vote_average': 7.795,
   'vote_count': 1523},
  {'adult': False,
   'backdrop_path': '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
   'genre_ids': [878, 12, 14],
   'id': 83533,
   'original_language': 'en',
   'original_title': 'Avatar: Fire and Ash',
   'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
   'popularity': 287.4937,
   'poster_path': '/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg',
   'release_date': '2025-12-17',
   'title': 'Avatar: Fire and Ash',
   'video': False,
   'vote_average': 7.355,
   'vote_count': 1503},
  {'adult': False,
   'backdrop_path': '/gQimJqYMKCkwHIo8wwYKhmnCfBr.jpg',
   'genre_ids': [28, 80, 53],
   'id': 1242501,
   'original_language': 'en',
   'original_title': 'Icefall',
   'overview': 'A young Indigenous game warden arrests an infamous poacher only to discover that the poacher knows the location of a plane carrying millions of dollars that has crashed in a frozen lake. When a group of criminals and dirty cops are alerted to the poacher’s whereabouts, the warden and the poacher team up to fight back and escape across the treacherous lake before the ice melts.',
   'popularity': 273.7226,
   'poster_path': '/5Byv6nznAb2Izd0gHpODOXnuSbo.jpg',
   'release_date': '2025-10-16',
   'title': 'Icefall',
   'video': False,
   'vote_average': 6.565,
   'vote_count': 84},
  {'adult': False,
   'backdrop_path': '/7nfpkR9XsQ1lBNCXSSHxGV7Dkxe.jpg',
   'genre_ids': [16, 35, 12, 10751, 9648],
   'id': 1084242,
   'original_language': 'en',
   'original_title': 'Zootopia 2',
   'overview': "After cracking the biggest case in Zootopia's history, rookie cops Judy Hopps and Nick Wilde find themselves on the twisting trail of a great mystery when Gary De'Snake arrives and turns the animal metropolis upside down. To crack the case, Judy and Nick must go undercover to unexpected new parts of town, where their growing partnership is tested like never before.",
   'popularity': 206.306,
   'poster_path': '/bjUWGw0Ao0qVWxagN3VCwBJHVo6.jpg',
   'release_date': '2025-11-26',
   'title': 'Zootopia 2',
   'video': False,
   'vote_average': 7.6,
   'vote_count': 1118},
  {'adult': False,
   'backdrop_path': '/sK3z0Naed3H1Wuh7a21YRVMxYqt.jpg',
   'genre_ids': [9648, 53],
   'id': 1368166,
   'original_language': 'en',
   'original_title': 'The Housemaid',
   'overview': 'Trying to escape her past, Millie Calloway accepts a job as a live-in housemaid for the wealthy Nina and Andrew Winchester. But what begins as a dream job quickly unravels into something far more dangerous—a sexy, seductive game of secrets, scandal, and power.',
   'popularity': 196.6764,
   'poster_path': '/cWsBscZzwu5brg9YjNkGewRUvJX.jpg',
   'release_date': '2025-12-18',
   'title': 'The Housemaid',
   'video': False,
   'vote_average': 7.182,
   'vote_count': 431},
  {'adult': False,
   'backdrop_path': '/vMxOmgmBGegjVObjlb8ugsjGgkD.jpg',
   'genre_ids': [10752, 28, 18],
   'id': 1252037,
   'original_language': 'de',
   'original_title': 'Der Tiger',
   'overview': "A German Tiger tank crew is sent on a dangerous mission to rescue the missing officer Paul von Hardenburg from a top-secret bunker behind enemy lines. As they make their way through the lethal no-man's land, they must confront not only the enemy, but also their own fears and inner demons. Fueled by the Wehrmacht's methamphetamine, their mission increasingly becomes a journey into the heart of darkness.",
   'popularity': 182.479,
   'poster_path': '/65Jr1JAgWlu9em8zHhAfrNJJQBt.jpg',
   'release_date': '2025-09-18',
   'title': 'The Tank',
   'video': False,
   'vote_average': 7.05,
   'vote_count': 242},
  {'adult': False,
   'backdrop_path': '/mFDQ8f2lPHorGwtuE0fjnUIbKLF.jpg',
   'genre_ids': [35],
   'id': 62029,
   'original_language': 'it',
   'original_title': 'Bingo Bongo',
   'overview': 'The ape-man, found somewhere in the jungles of Congo, transferred to Milan and named Bingo Bongo. The only one who believes in the human qualities of him is Laura, a woman anthropologist , so their affection for each other even grows to love.',
   'popularity': 151.6571,
   'poster_path': '/5ve4VuCwi7Xas5s50ynEB7uFjM2.jpg',
   'release_date': '1982-12-23',
   'title': 'Bingo Bongo',
   'video': False,
   'vote_average': 5.725,
   'vote_count': 167},
  {'adult': False,
   'backdrop_path': '/iZLqwEwUViJdSkGVjePGhxYzbDb.jpg',
   'genre_ids': [878, 53],
   'id': 755898,
   'original_language': 'en',
   'original_title': 'War of the Worlds',
   'overview': 'Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.',
   'popularity': 138.8108,
   'poster_path': '/yvirUYrva23IudARHn3mMGVxWqM.jpg',
   'release_date': '2025-07-29',
   'title': 'War of the Worlds',
   'video': False,
   'vote_average': 4.221,
   'vote_count': 846},
  {'adult': False,
   'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
   'genre_ids': [16, 28, 14],
   'id': 1311031,
   'original_language': 'ja',
   'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
   'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
   'popularity': 129.6106,
   'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
   'release_date': '2025-07-18',
   'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
   'video': False,
   'vote_average': 7.644,
   'vote_count': 662},
  {'adult': False,
   'backdrop_path': '/oIJjO1CvEdTMFNkWfHaV0RB584G.jpg',
   'genre_ids': [28, 80, 53],
   'id': 628847,
   'original_language': 'en',
   'original_title': 'Trap House',
   'overview': "An undercover DEA agent and his partner embark on a game of cat and mouse with an audacious, and surprising group of thieves - their own rebellious teenagers, who have begun robbing from a dangerous cartel, using their parents' tactics and top-secret intel to do it.",
   'popularity': 121.0502,
   'poster_path': '/6tpAPeuuqbVnYWWPoOLEDLSBU7a.jpg',
   'release_date': '2025-11-14',
   'title': 'Trap House',
   'video': False,
   'vote_average': 6.525,
   'vote_count': 162},
  {'adult': False,
   'backdrop_path': '/wCwZ4ljSsWyZyTiyk1tGQtBHTDx.jpg',
   'genre_ids': [28, 18],
   'id': 1511417,
   'original_language': 'te',
   'original_title': 'Baahubali: The Epic',
   'overview': 'When a mysterious child is found by a tribal couple near a roaring waterfall, they raise him as their own. As he grows, Sivudu is drawn to the world beyond the cliffs, where he discovers the ancient kingdom of Mahishmati, ruled by a cruel tyrant, haunted by rebellion, and bound to his past. What begins as a quest for love soon unravels a legacy of betrayal, sacrifice, and a forgotten prince.',
   'popularity': 118.2717,
   'poster_path': '/z9YIo2qscyaXYgRqIdRJtND3bw8.jpg',
   'release_date': '2025-10-29',
   'title': 'Bāhubali: The Epic',
   'video': False,
   'vote_average': 5.7,
   'vote_count': 22},
  {'adult': False,
   'backdrop_path': '/dT1p0K1szMAUBuE2bibouDQdNb8.jpg',
   'genre_ids': [27, 53, 878],
   'id': 1272837,
   'original_language': 'en',
   'original_title': '28 Years Later: The Bone Temple',
   'overview': "Dr. Kelson finds himself in a shocking new relationship - with consequences that could change the world as they know it - and Spike's encounter with Jimmy Crystal becomes a nightmare he can't escape.",
   'popularity': 113.7752,
   'poster_path': '/kK1BGkG3KAvWB0WMV1DfOx9yTMZ.jpg',
   'release_date': '2026-01-14',
   'title': '28 Years Later: The Bone Temple',
   'video': False,
   'vote_average': 7.023,
   'vote_count': 129},
  {'adult': False,
   'backdrop_path': '/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg',
   'genre_ids': [28, 80, 18, 53],
   'id': 1419406,
   'original_language': 'zh',
   'original_title': '捕风追影',
   'overview': 'Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves.',
   'popularity': 111.9857,
   'poster_path': '/e0RU6KpdnrqFxDKlI3NOqN8nHL6.jpg',
   'release_date': '2025-08-16',
   'title': "The Shadow's Edge",
   'video': False,
   'vote_average': 7.154,
   'vote_count': 302},
  {'adult': False,
   'backdrop_path': '/fP6L6V42980QmuoyyGXCmWphwpT.jpg',
   'genre_ids': [28, 12, 14],
   'id': 1131759,
   'original_language': 'ko',
   'original_title': '전지적 독자 시점',
   'overview': 'Kim Dok-ja, an ordinary man in his 20s, is the only reader of an obscure web novel titled "Three Ways to Survive the Apocalypse". After having read the last chapter, the novel suddenly becomes reality, and its omnipotent hero Yu Jung-hyeok appears before Kim. As the only person who knows how to survive in this world, Kim and his companions strive to save the world by writing his own, new ending.',
   'popularity': 110.2696,
   'poster_path': '/3R3dXO2nm8JyR5NG7SEfii7RzlV.jpg',
   'release_date': '2025-07-23',
   'title': 'Omniscient Reader: The Prophecy',
   'video': False,
   'vote_average': 6.7,
   'vote_count': 45},
  {'adult': False,
   'backdrop_path': '/dHSz0tSFuO2CsXJ1CApSauP9Ncl.jpg',
   'genre_ids': [53, 80, 9648],
   'id': 425274,
   'original_language': 'en',
   'original_title': "Now You See Me: Now You Don't",
   'overview': 'The original Four Horsemen reunite with a new generation of illusionists to take on powerful diamond heiress Veronika Vanderberg, who leads a criminal empire built on money laundering and trafficking. The new and old magicians must overcome their differences to work together on their most ambitious heist yet.',
   'popularity': 107.3078,
   'poster_path': '/oD3Eey4e4Z259XLm3eD3WGcoJAh.jpg',
   'release_date': '2025-11-12',
   'title': "Now You See Me: Now You Don't",
   'video': False,
   'vote_average': 6.576,
   'vote_count': 905},
  {'adult': False,
   'backdrop_path': '/c30cOCYtnydXAQBGFmdMQisy5pB.jpg',
   'genre_ids': [35, 18],
   'id': 1208348,
   'original_language': 'en',
   'original_title': 'Rental Family',
   'overview': "An American actor in Tokyo struggles to find purpose until he lands an unusual gig: working for a Japanese 'rental family' agency, playing stand-in roles for strangers. As he immerses himself in his clients' worlds, he begins to form genuine bonds that blur the lines between performance and reality.",
   'popularity': 105.3077,
   'poster_path': '/A5lswNlytTUrnMWsuD0NFfhZlf3.jpg',
   'release_date': '2025-11-20',
   'title': 'Rental Family',
   'video': False,
   'vote_average': 7.9,
   'vote_count': 168},
  {'adult': False,
   'backdrop_path': '/novE5UrqfLIFEMe5QBnjm18GG4E.jpg',
   'genre_ids': [28, 80, 53],
   'id': 1512623,
   'original_language': 'en',
   'original_title': 'Risqué',
   'overview': 'Fired from a strip club, a vengeful dancer masterminds a high-stakes heist with fellow strippers to take down the corrupt boss and the men who underestimate them.',
   'popularity': 96.5037,
   'poster_path': '/h6OsRrDwbspLnKMvlFl57QFDP7d.jpg',
   'release_date': '2025-08-01',
   'title': 'Risqué',
   'video': False,
   'vote_average': 7.544,
   'vote_count': 45},
  {'adult': False,
   'backdrop_path': '/A1prqBBKiwfnahBnNgM1t5y5vmA.jpg',
   'genre_ids': [27, 53, 35],
   'id': 1255674,
   'original_language': 'es',
   'original_title': 'Vieja loca',
   'overview': 'Pedro receives a desperate message from an ex-girlfriend asking him to look after her senile mother, Alicia. What seems like a simple mission soon becomes his worst nightmare. Pedro needs to escape; but Alicia won’t let him...',
   'popularity': 96.3444,
   'poster_path': '/a2EdW8sk22fNCvrpOiaHbR2hOuZ.jpg',
   'release_date': '2025-10-10',
   'title': 'Crazy Old Lady',
   'video': False,
   'vote_average': 5.4,
   'vote_count': 10},
  {'adult': False,
   'backdrop_path': '/8vLt9TYFZdAwYtqImvggTM5yFnF.jpg',
   'genre_ids': [878, 12, 18],
   'id': 982843,
   'original_language': 'ko',
   'original_title': '대홍수',
   'overview': 'When a raging flood traps a researcher and her young son, a call to a crucial mission puts their escape — and the future of humanity — on the line.',
   'popularity': 92.4227,
   'poster_path': '/1tUOZQDgZaGqZtrB21MieiXARL2.jpg',
   'release_date': '2025-09-18',
   'title': 'The Great Flood',
   'video': False,
   'vote_average': 6.029,
   'vote_count': 494}],
 'total_pages': 54744,
 'total_results': 1094873}

In [8]:
for i in rs['results']:
    print (i['original_title'])

The Rip
Predator: Badlands
Avatar: Fire and Ash
Icefall
Zootopia 2
The Housemaid
Der Tiger
Bingo Bongo
War of the Worlds
劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来
Trap House
Baahubali: The Epic
28 Years Later: The Bone Temple
捕风追影
전지적 독자 시점
Now You See Me: Now You Don't
Rental Family
Risqué
Vieja loca
대홍수

In [9]:
for i in rs['results']:
    print(i['overview'])

Trust frays when a team of Miami cops discovers millions in cash inside a run-down stash house, calling everyone — and everything — into question.
Cast out from his clan, a young Predator finds an unlikely ally in a damaged android and embarks on a treacherous journey in search of the ultimate adversary.
In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.
A young Indigenous game warden arrests an infamous poacher only to discover that the poacher knows the location of a plane carrying millions of dollars that has crashed in a frozen lake. When a group of criminals and dirty cops are alerted to the poacher’s whereabouts, the warden and the poacher team up to fight back and escape across the treacherous lake before the ice melts.
After cracking the biggest case in Zootopia's history, rookie cops Judy Hopps and Nick Wilde find themselves on the twisting trail of a great mystery when Gary De'Snake arrives and turns the animal metropolis upside down. To crack the case, Judy and Nick must go undercover to unexpected new parts of town, where their growing partnership is tested like never before.
Trying to escape her past, Millie Calloway accepts a job as a live-in housemaid for the wealthy Nina and Andrew Winchester. But what begins as a dream job quickly unravels into something far more dangerous—a sexy, seductive game of secrets, scandal, and power.
A German Tiger tank crew is sent on a dangerous mission to rescue the missing officer Paul von Hardenburg from a top-secret bunker behind enemy lines. As they make their way through the lethal no-man's land, they must confront not only the enemy, but also their own fears and inner demons. Fueled by the Wehrmacht's methamphetamine, their mission increasingly becomes a journey into the heart of darkness.
The ape-man, found somewhere in the jungles of Congo, transferred to Milan and named Bingo Bongo. The only one who believes in the human qualities of him is Laura, a woman anthropologist , so their affection for each other even grows to love.
Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.
The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.
An undercover DEA agent and his partner embark on a game of cat and mouse with an audacious, and surprising group of thieves - their own rebellious teenagers, who have begun robbing from a dangerous cartel, using their parents' tactics and top-secret intel to do it.
When a mysterious child is found by a tribal couple near a roaring waterfall, they raise him as their own. As he grows, Sivudu is drawn to the world beyond the cliffs, where he discovers the ancient kingdom of Mahishmati, ruled by a cruel tyrant, haunted by rebellion, and bound to his past. What begins as a quest for love soon unravels a legacy of betrayal, sacrifice, and a forgotten prince.
Dr. Kelson finds himself in a shocking new relationship - with consequences that could change the world as they know it - and Spike's encounter with Jimmy Crystal becomes a nightmare he can't escape.
Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves.
Kim Dok-ja, an ordinary man in his 20s, is the only reader of an obscure web novel titled "Three Ways to Survive the Apocalypse". After having read the last chapter, the novel suddenly becomes reality, and its omnipotent hero Yu Jung-hyeok appears before Kim. As the only person who knows how to survive in this world, Kim and his companions strive to save the world by writing his own, new ending.
The original Four Horsemen reunite with a new generation of illusionists to take on powerful diamond heiress Veronika Vanderberg, who leads a criminal empire built on money laundering and trafficking. The new and old magicians must overcome their differences to work together on their most ambitious heist yet.
An American actor in Tokyo struggles to find purpose until he lands an unusual gig: working for a Japanese 'rental family' agency, playing stand-in roles for strangers. As he immerses himself in his clients' worlds, he begins to form genuine bonds that blur the lines between performance and reality.
Fired from a strip club, a vengeful dancer masterminds a high-stakes heist with fellow strippers to take down the corrupt boss and the men who underestimate them.
Pedro receives a desperate message from an ex-girlfriend asking him to look after her senile mother, Alicia. What seems like a simple mission soon becomes his worst nightmare. Pedro needs to escape; but Alicia won’t let him...
When a raging flood traps a researcher and her young son, a call to a crucial mission puts their escape — and the future of humanity — on the line.

In [21]:
original_title=[]
release_date=[]
id=[]
overview=[]
popularity=[]
original_language=[]

for i in rs['results']:
    original_title.append(i['original_title'])
    release_date.append(i['release_date'])
    id.append(i['id'])
    overview.append(i['overview'])
    popularity.append(i['popularity'])
    original_language.append(['original_language'])

d = {
    'original_title': original_title,
    'release_date': release_date,
    'id': id,
    'overview': overview,
    'popularity': popularity,
    'original_language': original_language
}
df=pd.DataFrame(d)
df

,original_title,release_date,id,overview,popularity,original_language
0,The Rip,2026-01-13,1306368,Trust frays when a team of Miami cops discover...,577.3256,[original_language]
1,Predator: Badlands,2025-11-05,1242898,"Cast out from his clan, a young Predator finds...",405.5067,[original_language]
2,Avatar: Fire and Ash,2025-12-17,83533,In the wake of the devastating war against the...,287.4937,[original_language]
3,Icefall,2025-10-16,1242501,A young Indigenous game warden arrests an infa...,273.7226,[original_language]
4,Zootopia 2,2025-11-26,1084242,After cracking the biggest case in Zootopia's ...,206.3060,[original_language]
5,The Housemaid,2025-12-18,1368166,"Trying to escape her past, Millie Calloway acc...",196.6764,[original_language]
6,Der Tiger,2025-09-18,1252037,A German Tiger tank crew is sent on a dangerou...,182.4790,[original_language]
7,Bingo Bongo,1982-12-23,62029,"The ape-man, found somewhere in the jungles of...",151.6571,[original_language]
8,War of the Worlds,2025-07-29,755898,Will Radford is a top analyst for Homeland Sec...,138.8108,[original_language]
9,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,2025-07-18,1311031,The Demon Slayer Corps are drawn into the Infi...,129.6106,[original_language]
10,Trap House,2025-11-14,628847,An undercover DEA agent and his partner embark...,121.0502,[original_language]
11,Baahubali: The Epic,2025-10-29,1511417,When a mysterious child is found by a tribal c...,118.2717,[original_language]
12,28 Years Later: The Bone Temple,2026-01-14,1272837,Dr. Kelson finds himself in a shocking new rel...,113.7752,[original_language]
13,捕风追影,2025-08-16,1419406,Macau Police brings the tracking expert police...,111.9857,[original_language]
14,전지적 독자 시점,2025-07-23,1131759,"Kim Dok-ja, an ordinary man in his 20s, is the...",110.2696,[original_language]
15,Now You See Me: Now You Don't,2025-11-12,425274,The original Four Horsemen reunite with a new ...,107.3078,[original_language]
16,Rental Family,2025-11-20,1208348,An American actor in Tokyo struggles to find p...,105.3077,[original_language]
17,Risqué,2025-08-01,1512623,"Fired from a strip club, a vengeful dancer mas...",96.5037,[original_language]
18,Vieja loca,2025-10-10,1255674,Pedro receives a desperate message from an ex-...,96.3444,[original_language]
19,대홍수,2025-09-18,982843,When a raging flood traps a researcher and her...,92.4227,[original_language]

In [42]:
final = pd.DataFrame()

for j in range(1,11):
    rs = requests.get(
        'https://api.themoviedb.org/3/movie/popular?api_key=703f0b4742b9931be466f7027ee52797&page={}'.format(j)
    ).json()

    original_title = []
    release_date = []
    movie_id = []         
    overview = []
    popularity = []
    original_language = []

    for i in rs['results']:
        original_title.append(i['original_title'])
        release_date.append(i['release_date'])
        movie_id.append(i['id'])
        overview.append(i['overview'])
        popularity.append(i['popularity'])
        original_language.append(i['original_language'])

    d = {
        'original_title': original_title,
        'release_date': release_date,
        'id': movie_id,
        'overview': overview,
        'popularity': popularity,
        'original_language': original_language
    }

    df = pd.DataFrame(d)

    # ✅ MUST assign back
    # final = final.append(df, ignore_index=True)

    final = pd.concat([final, df], ignore_index=True)

In [41]:
final.shape

(2000, 6)

In [43]:
final

,original_title,release_date,id,overview,popularity,original_language
0,The Rip,2026-01-13,1306368,Trust frays when a team of Miami cops discover...,577.3256,en
1,Predator: Badlands,2025-11-05,1242898,"Cast out from his clan, a young Predator finds...",405.5067,en
2,Avatar: Fire and Ash,2025-12-17,83533,In the wake of the devastating war against the...,287.4937,en
3,Icefall,2025-10-16,1242501,A young Indigenous game warden arrests an infa...,273.7226,en
4,Zootopia 2,2025-11-26,1084242,After cracking the biggest case in Zootopia's ...,206.3060,en
...,...,...,...,...,...,...
195,Frozen,2013-11-20,109445,Young princess Anna of Arendelle dreams about ...,19.3480,en
196,The Other,2025-04-26,1162858,"Unable to conceive, a couple seeks to build a ...",19.3461,en
197,君の名は。,2016-08-26,372058,High schoolers Mitsuha and Taki are complete s...,19.0824,ja
198,危机航线,2024-09-29,949709,"""Anyone? There is ......"" A mysterious message...",18.9186,zh
199,Despicable Me 4,2024-06-20,519182,"Gru and Lucy and their girls—Margo, Edith and ...",18.8339,en

In [44]:
final.to_csv('movies.csv')

In [46]:
final

,original_title,release_date,id,overview,popularity,original_language
0,The Rip,2026-01-13,1306368,Trust frays when a team of Miami cops discover...,577.3256,en
1,Predator: Badlands,2025-11-05,1242898,"Cast out from his clan, a young Predator finds...",405.5067,en
2,Avatar: Fire and Ash,2025-12-17,83533,In the wake of the devastating war against the...,287.4937,en
3,Icefall,2025-10-16,1242501,A young Indigenous game warden arrests an infa...,273.7226,en
4,Zootopia 2,2025-11-26,1084242,After cracking the biggest case in Zootopia's ...,206.3060,en
...,...,...,...,...,...,...
195,Frozen,2013-11-20,109445,Young princess Anna of Arendelle dreams about ...,19.3480,en
196,The Other,2025-04-26,1162858,"Unable to conceive, a couple seeks to build a ...",19.3461,en
197,君の名は。,2016-08-26,372058,High schoolers Mitsuha and Taki are complete s...,19.0824,ja
198,危机航线,2024-09-29,949709,"""Anyone? There is ......"" A mysterious message...",18.9186,zh
199,Despicable Me 4,2024-06-20,519182,"Gru and Lucy and their girls—Margo, Edith and ...",18.8339,en

In [47]:
final.head()

,original_title,release_date,id,overview,popularity,original_language
0,The Rip,2026-01-13,1306368,Trust frays when a team of Miami cops discover...,577.3256,en
1,Predator: Badlands,2025-11-05,1242898,"Cast out from his clan, a young Predator finds...",405.5067,en
2,Avatar: Fire and Ash,2025-12-17,83533,In the wake of the devastating war against the...,287.4937,en
3,Icefall,2025-10-16,1242501,A young Indigenous game warden arrests an infa...,273.7226,en
4,Zootopia 2,2025-11-26,1084242,After cracking the biggest case in Zootopia's ...,206.3060,en

In [2]:
final.shape

NameError: name 'final' is not defined

In [3]:
final.shape

NameError: name 'final' is not defined